# readthedocs configuration file version
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  # install R
  apt_packages:
    - r-base
    - default-jdk

python:
  install:
    - requirements: docs/requirements.txt

# Build the docs in all formats (html, pdf, epub, etc.)
formats: all