# readthedocs configuration file version
version: 2

sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  # install R
  apt_packages:
    - r-base
    - default-jdk
    - graphviz


python:
  install:
    - requirements: docs/requirements.txt

# Build the docs in all formats (html, pdf, epub, etc.)
formats: all