services:

  # OHDSI API
  ohdsi-api:
    command: ["gunicorn", "-b", "0.0.0.0", "-w", "1", "--reload", "api.src:app"]

  celery-worker:
    command: watchmedo auto-restart --directory=/app --pattern=*.py --recursive --verbose -- celery -A api.src.celery_app --workdir /app worker

