services:

  # OHDSI API
  ohdsi-api:
    build: .
    image: harbor2.vantage6.ai/infrastructure/ohdsi-api:latest
    ports:
      - 5000:8000
    volumes:
      - .:/app
    container_name: ohdsi-api
    env_file:
      - .env
    command: ["gunicorn", "-b", "0.0.0.0", "-w", "1", "api.src:app"]

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    container_name: rabbitmq

  # PostgreSQL
  db:
    image: postgres:9.6
    ports:
      - 5432:5432
    container_name: postgres
    environment:
      - POSTGRES_USER=ohdsi
      - POSTGRES_PASSWORD=ohdsi
      - POSTGRES_DB=ohdsi
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  celery-worker:
    build: .
    image: harbor2.vantage6.ai/infrastructure/ohdsi-api:latest
    container_name: celery-worker
    command: celery -A api.src.celery_app worker -l DEBUG -P solo
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - db


